version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
      - image: circleci/postgres:9.6.3-alpine
        environment:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
          PGPORT: 5433
          NF_COMMENTS_PGPORT: 5433
    working_directory: ~/repo
    steps:
      - checkout

      - restore_cache:
          keys:
            - dependencies-{{ checksum "server/package.json" }}-{{ checksum "client/package.json" }}
            - dependencies-

      - run:
          command: |
            cd client && npm install && cd ../server && npm install

      - save_cache:
          paths:
            - server/node_modules
            - client/node_modules
          key: dependencies-{{ checksum "server/package.json" }}-{{ checksum "client/package.json" }}

      - run:
          command: |
            cd server && npm test && cd ../client && npm test
