version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
      - image: circleci/postgres:9.6.3-alpine
        environment:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
          PGPORT: 5432
          NODE_ENV: test
    working_directory: ~/repo
    steps:
      - checkout

      - restore_cache:
          key: dependencies-{{ .Environment.CACHE_VERSION }}-{{ checksum "package-lock.json" }}
      - restore_cache:
          key: dependencies-{{ .Environment.CACHE_VERSION }}-{{ checksum "packages/comments-backend-core/package-lock.json" }}
      - restore_cache:
          key: dependencies-{{ .Environment.CACHE_VERSION }}-{{ checksum "packages/comments-backend-hapi-plugin/package-lock.json" }}
      - restore_cache:
          key: dependencies-{{ .Environment.CACHE_VERSION }}-{{ checksum "packages/comments-backend-hapi-server/package-lock.json" }}
      - restore_cache:
          key: dependencies-{{ .Environment.CACHE_VERSION }}-{{ checksum "packages/comments-react-components/package-lock.json" }}

      - run:
          command: npm install

      - save_cache:
          key: dependencies-{{ .Environment.CACHE_VERSION }}-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - save_cache:
          key: dependencies-{{ .Environment.CACHE_VERSION }}-{{ checksum "packages/comments-backend-core/package-lock.json" }}
          paths:
            - packages/comments-backend-core/node_modules
      - save_cache:
          key: dependencies-{{ .Environment.CACHE_VERSION }}-{{ checksum "packages/comments-backend-hapi-plugin/package-lock.json" }}
          paths:
            - packages/comments-backend-hapi-plugin/node_modules
      - save_cache:
          key: dependencies-{{ .Environment.CACHE_VERSION }}-{{ checksum "packages/comments-backend-hapi-server/package-lock.json" }}
          paths:
            - packages/comments-backend-hapi-server/node_modules
      - save_cache:
          key: dependencies-{{ .Environment.CACHE_VERSION }}-{{ checksum "packages/comments-react-components/package-lock.json" }}
          paths:
            - packages/comments-react-components/node_modules

      - run:
          command: npm run pg:test:init

      - run:
          command: npm run sanity